name: pkg.pr.new

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: pkg-pr-new-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: corepack enable

      - run: pnpm override-wasm

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm build-wasm

      - run: pnpm exec pkg-pr-new publish --no-compact ./crates/bass-pitch-wasm

      - run: sudo apt-get update && sudo apt-get install -y faust

      - run: pnpm build-faust

      - run: pnpm exec pkg-pr-new publish --no-compact ./crates/faust
